# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'PopADots' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PopADots
  pod 'Firebase/Core'
  pod 'Firebase/Crash'
  pod 'Firebase/AdMob'
  #pod 'GooglePlayGames'
end
